# --- 1. BASE USERS ---
N_ROWS_CLIENTE = 300_000
N_ROWS_ORGANIZADOR = int(N_ROWS_CLIENTE / 60)
N_ROWS_USUARIO = N_ROWS_CLIENTE + N_ROWS_ORGANIZADOR

# --- 2. EVENTS ---
N_ROWS_EVENTOS = N_ROWS_ORGANIZADOR * 5 
N_PRESENCIAL = int(N_ROWS_EVENTOS * 0.6)
N_ONLINE = N_ROWS_EVENTOS - N_PRESENCIAL

# --- 3. BUSINESS LOGIC ---
LOTES_POR_EVENTO = 2
N_PEDIDOS = int(N_ROWS_CLIENTE * 2.5)

# --- 4. OPERATIONS ---
N_ATENDENTES = int(N_ROWS_CLIENTE / 3000)
N_CHAMADOS_SUPORTE = int(N_PEDIDOS * 0.04)

# --- GLOBAL SETTINGS ---
SEED = 42